---
- name: Configure MOTD on RHEL Servers
  hosts: all
 # become: yes
  vars:
    motd_message: |
    
      Welcome to SBSynergy LLC
      This server is being monitored
      Please respect the privacy of others.

  tasks:
    - name: Set MOTD on RHEL Servers
      copy:
        dest: /etc/motd
        content: "{{ motd_message }}"
        mode: '0644'
    
