---
- name: Disable GRUB password on Red Hat servers
  hosts: mail
 # become: yes
  vars:
    grub_cfg: /etc/grub.d/10_linux
    backup_ext: ".backup"

  tasks:
    - name: Ensure the GRUB configuration file exists
      ansible.builtin.stat:
        path: "{{ grub_cfg }}"
      register: grub_cfg_stat

    - name: Backup the GRUB configuration file
      ansible.builtin.copy:
        src: "{{ grub_cfg }}"
        dest: "{{ grub_cfg }}{{ backup_ext }}"
        remote_src: yes
      when: grub_cfg_stat.stat.exists

    - name: Remove or comment GRUB password lines from the GRUB configuration
      ansible.builtin.lineinfile:
        path: "{{ grub_cfg }}"
        regexp: '^(.*password.*)$'
        line: '#\1'
        backrefs: yes
      register: grub_modified

    - name: Update GRUB
      ansible.builtin.shell:
        cmd: grub2-mkconfig -o /boot/grub2/grub.cfg
      when: grub_modified.changed

    - name: Reboot the system for changes to take effect
      ansible.builtin.reboot:
      when: grub_modified.changed
      vars:
        reboot_timeout: 600
