---
- name: Install RPM package on Red Hat servers
  hosts: all
#  become: yes

  vars:
    rpm_package_local_path: "/root/check-mk-agent-2.2.0p12-bfa944d3b37e4b92.noarch.rpm" # Replace with your local RPM package path
    rpm_package_remote_path: "/root/check-mk-agent-2.2.0p12-bfa944d3b37e4b92.noarch.rpm" # Temporary path on remote server

  tasks:
    - name: Copy RPM package to remote server
      ansible.builtin.copy:
        src: "{{ rpm_package_local_path }}"
        dest: "{{ rpm_package_remote_path }}"
        remote_src: false
        
    - name: Install RPM package
      ansible.builtin.yum:
        name: "{{ rpm_package_remote_path }}"
        state: present
