---
- name: copy SSH public key to remote server
  hosts: all


  vars:
    ssh_public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tasks:
    - name: Add SSH public key to authorized_keys
      authorized_key:
       user: root
       state: present
       key: "{{ ssh_public_key }}"
