---
- name: Update Hostname and Transfer SSH Key
  hosts: sambacifs
  #become: yes

  tasks:
    - name: Set new hostname
      hostname:
        name: 'sambacifs'

   # - name: Install sshpass (if not already installed)
    #  yum:
     #   name: sshpass
      #  state: present

    - name: Transfer root's SSH key to remote host
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

  
