---
- name: Set GRUB password for RHEL 7 servers
  hosts: mail
  become: yes
  tasks:
    - name: Check if GRUB password is set
      command: grep -q '^GRUB2_PASSWORD=' /etc/grub.d/01_users
      register: grub_password_check
      failed_when: grub_password_check.rc > 1
      changed_when: false
      check_mode: no

    - name: Set GRUB password
      block:
        - name: Backup the 01_users file
          copy:
            src: /etc/grub.d/01_users
            dest: /etc/grub.d/01_users.backup
            remote_src: yes

        - name: Set the GRUB2 password
          lineinfile:
            path: /etc/grub.d/01_users
            create: yes
            line: "GRUB2_PASSWORD=$1$P9fHssNu$I2rJGwBmmO8AgJ9LHnH710"
            regexp: '^GRUB2_PASSWORD='
          notify:
            - Update GRUB configuration

      when: grub_password_check.stdout == ""

  handlers:
    - name: Update GRUB configuration
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
      listen: "Update GRUB configuration"
